# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpagegalleryimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPageGalleryImage',
            new_name='PostlleryImage',
        ),
    ]
