# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('blog', '0005_auto_20170515_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTagIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameModel(
            old_name='PostlleryImage',
            new_name='PostGalleryImage',
        ),
    ]
