# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogCategory',
            new_name='PostCategory',
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name_plural': 'post categories'},
        ),
    ]
