# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogindexpage_header_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='header_image',
        ),
    ]
