# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170516_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='header_image',
        ),
    ]
